export const map = [
    // 1차 map -------------------------------------------
    // 중국
    {
      countryCode : 1,
      name : 'China',
      currentCode : { lat: 32.251631, lng: 104.418742},
      moveCode : { lat: 32.251631, lng: 104.418742 },
      storeCount : 1,
      zoom : 5,
      currentZoom : 2
    },
    // 한국
    {
      countryCode : 2,
      name : 'Korea',
      currentCode : { lat: 30.674775, lng: 126.651947},
      moveCode : { lat: 36.227189, lng: 127.977189 },
      storeCount : 7,
      zoom : 8,
      currentZoom : 2
    },
    // USA
    {
      countryCode : 3,
      name : 'U.S.A',
      currentCode : { lat: 35.16032, lng: -102.01904},
      moveCode : { lat: 35.16032, lng: -102.01904 },
      storeCount : 4,
      zoom : 5,
      currentZoom : 2
    },
    // 헝가리
    {
      countryCode : 4,
      name : 'Hungary',
      currentCode : { lat: 46.60709, lng: 18.74245},
      moveCode : { lat: 47.10709, lng: 19.94245 },
      storeCount : 1,
      zoom : 8,
      currentZoom : 2
    },
    // 인도
    {
      countryCode : 5,
      name : 'India',
      currentCode : { lat: 18.098829, lng: 79.600836  },
      moveCode : { lat: 19.498829, lng: 78.700836 },
      storeCount : 2,
      zoom : 5,
      currentZoom : 2
    },
    // 태국
    {
      countryCode : 6,
      name : 'Thailand',
      currentCode : { lat: 12.879886, lng: 101.081613 },
      moveCode : { lat: 15.39683, lng: 100.92706 },
      storeCount : 1,
      zoom : 7,
      currentZoom : 2,
    },
    // 인도네시아
    {
      countryCode : 7,
      name : 'Indo Nesia',
      currentCode : { lat: -9.36217, lng: 115.84880 },
      moveCode : { lat: -6.33070, lng: 107.1490 },
      storeCount : 2,
      zoom : 8,
      currentZoom : 2
    },
    // 베트남
    {
      countryCode : 8,
      name : 'Vietnam',
      currentCode : { lat: 14.78302, lng: 112.249716 },
      moveCode : { lat: 16.43158, lng: 107.58162 },
      storeCount : 1,
      zoom : 6,
      currentZoom : 2
    },
    // 일본
    {
      countryCode : 9,
      name : 'Japan',
      currentCode : { lat: 34.24323, lng: 140.43654 },
      moveCode : { lat: 37.92622, lng: 137.77508 },
      storeCount : 10,
      zoom : 6,
      currentZoom : 2
    },
    // 멕시코
    {
      countryCode : 10,
      name : 'Mexico',
      currentCode : { lat: 18.59909, lng: -102.53742 },
      moveCode : { lat: 24.01235, lng: -100.11249 },
      storeCount : 2,
      zoom : 6,
      currentZoom : 2
    },

    // 2차 map -------------------------------------------

    // 한국
    // 한국 - 인천
    {
        countryCode : 2,
        name : 'Korea',
        currentCode : { lat: 37.391895, lng: 126.697892 },
        moveCode : { lat: 37.391895, lng: 126.697892 },
        storeCount : 2,
        zoom : 13,
        currentZoom : 8
    },
    // 한국 - 평택
    {
        countryCode : 2,
        name : 'Korea',
        currentCode : { lat: 36.976806, lng: 126.845838 },
        moveCode : { lat: 36.976806, lng: 126.845838 },
        storeCount : 2,
        zoom : 14,
        currentZoom : 8
    },
    // 한국 - 그 외
    {
        countryCode : 2,
        name : 'Korea',
        currentCode : { lat: 35.582548, lng: 129.376002 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 8,
        info: {
            title: "Daedong Hi-Lex Inc. (Ulsan Plant)",
            address2: "",
            address: "236, Modulehwa Saneop-ro, Buk-gu, Ulsan, 44246 Korea",
            tel: "82(52)287-7635",
            fax: "82(52)287-7636",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 2,
        name : 'Korea',
        currentCode : { lat: 35.119932, lng: 126.775792 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 8,
        info: {
            title: "Daedong Hi-Lex Inc. (Gwangju Plant)",
            address2: "",
            address: "111, Pyeongdongsandan 6beon-ro, Gwangsan-gu, Gwangju, 62453 Korea",
            tel: "82(62)945-7635",
            fax: "-",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 2,
        name : 'Korea',
        currentCode : { lat: 35.215162, lng: 128.591787 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 8,
        info: {
            title: "TSK(Korea)Co., Ltd.",
            address2: "",
            address: "89, Jayumuyeok 3-gil, Masanhoewon-gu, Changwon-si, Gyeongsangnam-do, 51338 Korea",
            tel: "82(55)293-1473",
            fax: "82(32)813-763",
            established: "Now., 1972",
            netSales: "42 million US $",
            employee: "154",
            image: "/images/sub/company/affiliate/TSK(KOREA)CO., LTD..webp"
        },
    },

    // 중국
    {
        countryCode : 1,
        name : 'China',
        currentCode : { lat: 29.5725200, lng: 106.54846 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 5,
        info: {
            title: "Chongqing Hi-Lex Control Cable System Co., Ltd.",
            address2: "",
            address: "No.C29 Economy Development Yard Yubei District Chongqing, 400020 China",
            tel: "86(23)67463128",
            fax: "86(23)67463288",
            established: "Sep., 2002",
            netSales: "34 million US $",
            employee: "219",
            image: "/images/sub/company/affiliate/CHONGQING HI-LEX CONTROL CABLE SYSTEM CO., LTD..webp"
        },
    },

    // 미국
    {
        countryCode : 3,
        name : 'U.S.A',
        currentCode : { lat: 32.734761, lng: -85.29462 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 5,
        info: {
            title: "Daedong Hi-Lex Of America, Inc.",
            address2: "",
            address: "1195 Cr177, Cusseta, Alabama, 36852, U.S.A.",
            tel: "1-334-756-5300",
            fax: "1-334-756-5301",
            established: "Jun., 2008",
            netSales: "90 million US $",
            employee: "106",
        },
    },
    {
        countryCode : 3,
        name : 'U.S.A',
        currentCode : { lat: 42.034833, lng: -84.766488 },
        moveCode : { lat: 42.034833, lng: -84.766488 },
        storeCount : 3,
        zoom : 8,
        currentZoom : 5,
    },

    // 헝가리
    {
        countryCode : 4,
        name : 'Hungary',
        currentCode : { lat: 47.915895, lng: 19.116703 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 8,
        info: {
            title: "Hi-Lex Hungary Kft",
            address2: "",
            address: "Ipari Park 3 Retsag 2651 Hungary",
            tel: "+36-35-551-200",
            fax: "+36-35-551-201",
            established: "Jul., 2006",
            netSales: "16 million US $",
            employee: "156",
            image: "/images/sub/company/affiliate/HI-LEX HUNGARY CABLE SYSTEM MANUFACTURING LLC.webp"
        },
    },

    // 인도
    {
        countryCode : 5,
        name : 'India',
        currentCode : { lat: 23.237594, lng: 72.36742  },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 5,
        info: {
            title: "Hi-Lex India(P)Ltd.",
            address2: "",
            address: "Plot No.398 Sector-8, Imt Manesar, Gurgaon-122050, Haryana, India",
            tel: "91(124)4565000",
            fax: "91(124)4565004",
            established: "Nov., 1998",
            netSales: "39 million US $",
            employee: "456",
        },
    },
    {
        countryCode : 5,
        name : 'India',
        currentCode : { lat: 12.840723, lng: 79.913205  },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 5,
        info: {
            title: "Hi-Lex Door India Pvt Ltd.",
            address2: "",
            address: "Plot No.398 Sector-8, Imt Manesar, Gurgaon-122050, Haryana, India",
            tel: "",
            fax: "",
            established: "",
            netSales: "",
            employee: "",
        },
    },

    // 태국
    {
        countryCode : 6,
        name : 'Thailand',
        currentCode : { lat: 13.443532, lng: 101.08316 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 7,
        info: {
            title: "Thai Steel Cable Public Company Limited",
            address2: "",
            address: "Amata Industrial Estate, 700/737 Moo 1, Tambol Panthong, Amphur Panthong, Chonburi 20160 Thailand",
            tel: "66(2)738-9460/76",
            fax: "66(2)738-9482",
            established: "Nov., 1981",
            netSales: "85 million US $",
            employee: "1,140",
            image: "/images/sub/company/affiliate/THAI STEEL CABLE PUBLIC COMPANY LIMITED.webp"
        },
    },

    // 인도네시아
    {
        countryCode : 7,
        name : 'IndoNesia',
        currentCode : { lat: -6.33070, lng: 107.1490 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 8,
        info: {
            title: "PT.Hi-Lex Indonesia",
            address2: "",
            address: "Jl., Bouraq No.35 Ds.Karanganyar Kec.Neglasari Tangerang, Indonesia",
            tel: "62(21)-552-2325",
            fax: "62(21)-552-2324",
            established: "Nov., 1978",
            netSales: "85 million US $",
            employee: "1,219",
            image: "/images/sub/company/affiliate/THAI STEEL CABLE PUBLIC COMPANY LIMITED.webp"
        },
    },
    {
        countryCode : 7,
        name : 'IndoNesia',
        currentCode : { lat: -6.162498, lng: 106.647924 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 8,
        info: {
            title: "PT.Hi-Lex Parts Indonesia",
            address2: "",
            address: "Rjpx+W5r, Jl. Pembangunan 2, Rt.001/Rw.002, Karang Anyar, Kec. Neglasari, Kota Tangerang, Banten 15121 Indonesia",
            tel: "62(21)-552-2325",
            fax: "62(21)-399-8307",
            established: "Dec., 1988",
            netSales: "12 million US $",
            employee: "433",
            image: "/images/sub/company/affiliate/PT.HI-LEX PARTS INDONESIA.webp"
        },
    },

    // 베트남
    {
        countryCode : 8,
        name : 'Vietnam',
        currentCode : { lat: 20.897380, lng: 106.592423 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 6,
        info: {
            title: "Hi-Lex Vietnam Co., Ltd.",
            address2: "",
            address: "Management Bldg, Nomura, Haiphong Iz Km 13, Anduong, Haiphong City, Vietnam",
            tel: "84(31)-3743058",
            fax: "84(31)-3743059",
            established: "Mar., 1999",
            netSales: "20 million US $",
            employee: "405",
            image: "/images/sub/company/affiliate/HI-LEX VIETNAM CO., LTD. (VIETNAM).webp"
        },
    },

    // 일본
    // 일본 - 오사카
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 34.894505, lng: 135.22432 },
        moveCode : { lat: 34.894505, lng: 135.22432 },
        storeCount : 5,
        zoom : 11,
        currentZoom : 6
    },
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 34.7969522, lng: 137.559080 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 6,
        info: {
            title: "Hi-Lex Mikkabi Plant (Hamamatsu Office)",
            address2: "",
            address: "310 Mikkabicho Ushi, Hamana Ward, Hamamatsu, Shizuoka 431-1404, Japan.",
            tel: "(053)525-2111",
            fax: "(053)525-0427",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 36.5560645, lng: 139.945721 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 6,
        info: {
            title: "Hi-Lex Utsunomiya Technical Center(Utsunomiya Office)",
            address2: "",
            address: "145-6 Shimohiraide-machi, Utsunomiya, Tochigi 321-0903, Japan.",
            tel: "(028)663-4062",
            fax: "(028)663-4065",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 34.9127066, lng: 132.108657 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 6,
        info: {
            title: "Hi-Lex Shimane, Inc.",
            address2: "",
            address: "1820-16 Shimokoucho, Hamada, Shimane 697-0006, Japan.",
            tel: "(0855)23-5855",
            fax: "(0855)23-5890",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 36.220445, lng: 139.143910 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 6,
        info: {
            title: "Hi-Lex Saitama, Inc.",
            address2: "",
            address: "100 Kyōei, Honjo, Saitama 367-0037, Japan.",
            tel: "(0495)21-2611",
            fax: "(0495)24-0410",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 35.4376363, lng: 140.282358 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 6,
        info: {
            title: "Hi-Lex Kanto, Inc.",
            address2: "",
            address: "1520-4 Kobayashi, Mobara, Chiba 297-0074, Japan.",
            tel: "(0475)24-5155",
            fax: "(0475)23-2828",
            established: "",
            netSales: "",
            employee: "",
        },
    },

    // 멕시코
    {
        countryCode : 10,
        name : 'Mexico',
        currentCode : { lat: 20.559623, lng: -100.25774 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 6,
        info: {
            title: "Hi-Lex Mexicana Planta El Marqués",
            address2: "",
            address: "Circuito El Marqués Sur No. 18, Fracc. Parque Industrial El Marqués Ampliación, 76246 Querétaro, Qro., Mexico",
            tel: "",
            fax: "",
            established: "",
            netSales: "",
            employee: "",
            image: "/images/sub/company/affiliate/HI-LEX MEXICANA S.A. DE C.V. PLANTA EL MARQUÉS.webp"
        },
    },
    {
        countryCode : 10,
        name : 'Mexico',
        currentCode : { lat: 20.6225784, lng: -100.401530 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 6,
        info: {
            title: "Hi-Lex Mexicana Planta Queretaro",
            address2: "",
            address: "Av. Peñuelas 9, Carlos María De Bustamante, 76140 Santiago De Querétaro, Qro., Mexico",
            tel: "",
            fax: "",
            established: "",
            netSales: "",
            employee: "",
            image: "/images/sub/company/affiliate/HI-LEX MEXICANA S.A. DE C.V..webp"
        },
    },

    // 3차 ------------------------------------------------------------------
    // 한국 - 인천 (2)
    {
        countryCode : 2,
        name : 'Korea',
        currentCode : { lat: 37.391895, lng: 126.697892 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 13,
        info: {
            title: "Daedong Hi-Lex Inc.",
            address2: "{ 5LT,151BL,NAMDONG COMPLEX }",
            address: "43, Namdongdong-ro 78beon-gil, Namdong-gu, Incheon, 21692 Korea",
            tel: "82(32)818-7631",
            fax: "82(32)813-763",
            established: " Jul., 2003",
            netSales: "111 million US $",
            employee: "214",
            image: "/images/sub/company/affiliate/DAEDONG HI-LEX INC..webp"
        },
    },
    {
        countryCode : 2,
        name : 'Korea',
        currentCode : { lat: 37.420363, lng: 126.708536 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 13,
        info: {
            title: "Daedong System Co., Ltd.",
            address2: "{3LT,3BL,NAMDONG COMPLEX}",
            address: "419, Namdong-daero, Namdong-gu, Incheon, 21629 Korea",
            tel: "82(32)818-7631",
            fax: "82(32)813-763",
            established: " Jul., 2003",
            netSales: "111 million US $",
            employee: "214",
        },
    },
    // 한국 - 평택(2)
    {
        countryCode : 2,
        name : 'Korea',
        currentCode : { lat: 36.976806, lng: 126.845838 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 14,
        info: {
            title: "Daedong Door Hi-Lex Inc.",
            address2: "{3LT,3BL,NAMDONG COMPLEX}",
            address: "21, Pyeongtaekhang-ro 184beon-gil, Poseung-eup, Pyeongtaek-si, Gyeonggi-do, 17959 Korea",
            tel: "82(31)680-8200",
            fax: "FAX: 82(32)499-4155",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 2,
        name : 'Korea',
        currentCode : { lat: 36.973021, lng: 126.857207 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 14,
        info: {
            title: "Daedong Hi-Lex Inc. (Poseung Plant)",
            address2: "",
            address: "169, Poseunggongdansunhwan-ro, Poseung-eup, Pyeongtaek-si, Gyeonggi-do, 17960 Korea",
            tel: "82(31)686-7674",
            fax: "82(31)686-7674",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    // 일본 - 오사카 (5)
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 34.80952, lng: 135.34699 },
        moveCode : { lat: 34.80952, lng: 135.34699 },
        storeCount : 2,
        zoom : 17,
        currentZoom : 11
    },
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 35.13340716, lng: 135.06652 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 11,
        info: {
            title: "Hi-Lex Kaibara Plant",
            address2: "",
            address: "1700 Kaibaracho Kaibara, Tamba, Hyogo 669-3309, Japan",
            tel: "(0795)72-2130",
            fax: "(0795)72-3549",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 34.894505, lng: 135.22432 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 11,
        info: {
            title: "Hi-Lex Sanda Plant",
            address2: "",
            address: "4-3-9 Miwa, Sanda, Hyogo 669-1513, Japan.",
            tel: "(079)563-3001",
            fax: "(079)563-7264",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 34.929637, lng: 135.163531 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 11,
        info: {
            title: "Hi-Lex Sanda-Nishi Plant",
            address2: "",
            address: "14-4 Technopark, Sanda, Hyogo, 669-1339, Japan.",
            tel: "(079)568-2480",
            fax: "(079)568-2482",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    // 미국
    {
        countryCode : 3,
        name : 'U.S.A',
        currentCode : { lat: 42.034833, lng: -84.766488 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 8,
        info: {
            title: "Hi-Lex Controls Inc.",
            address2: "",
            address: "152 Simpson Drive, Litchfield, Michigan 49252 U.S.A.",
            tel: "",
            fax: "",
            established: "May., 1989",
            netSales: "323million US $",
            employee: "589",
        },
    },
    {
        countryCode : 3,
        name : 'U.S.A',
        currentCode : { lat: 42.337376, lng: -85.282724 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 8,
        info: {
            title: "Hi-Lex America Inc.",
            address2: "",
            address: "5200 Wayne Road, Battle Creek, Michigan 49037 U.S.A.",
            tel: "1(269)968-0781",
            fax: "1(269)968-0885",
            established: "Apr., 1975",
            netSales: "151 million US $",
            employee: "274",
        },

    },
    {
        countryCode : 3,
        name : 'U.S.A',
        currentCode : { lat: 42.642517, lng: -83.190976 },
        moveCode : {},
        storeCount : 0,
        zoom : 0,
        currentZoom : 8,
        info: {
            title: "Hi-Lex Automotive Center",
            address2: "",
            address: "2911 Research Dr, Rochester Hills, Mi 48309 U.S.A.",
            tel: "1(248)-267-3800",
            fax: "1(267)-756-3889",
            established: "",
            netSales: "",
            employee: "",
        },
    },

    // 4차 -------------------------------------------------------------------
    // 일본 - 오사카 (2)
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 34.80952, lng: 135.34699 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 17,
        info: {
            title: "Hi-Lex Corporation",
            address2: "",
            address: "1-12-28 Sakaemachi, Takarazuka City, Hyogo 665-0845, Japan.",
            tel: "(0797)85-2500",
            fax: "(0797)83-2474",
            established: "",
            netSales: "",
            employee: "",
        },
    },
    {
        countryCode : 9,
        name : 'Japan',
        currentCode : { lat: 34.8096715, lng: 135.346512 },
        moveCode : { },
        storeCount : 0,
        zoom : 0,
        currentZoom : 17,
        info: {
            title: "Hi-Lex Medical",
            address2: "",
            address: "1-chōme-13-25 Sakaemachi, Takarazuka, Hyogo 665-0845, Japan",
            tel: "(0797)85-2571",
            fax: "(0797)85-2990",
            established: "",
            netSales: "",
            employee: "",
        },
    },
]
